<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");?>
<?$APPLICATION->SetTitle("Каталог");?>
<?require_once($_SERVER["DOCUMENT_ROOT"]."/work-scripts/StructureData.php");?>
<? $APPLICATION->IncludeComponent(
	"bitrix:catalog", 
	"main", 
	array(
		"IBLOCK_TYPE" => "aspro_kshop_catalog",
		"IBLOCK_ID" => "11",
		"HIDE_NOT_AVAILABLE" => "N",
		"BASKET_URL" => "/basket/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/catalog/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "250000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_TITLE" => "Y",
		"SET_STATUS_404" => "Y",
		"USE_ELEMENT_COUNTER" => "Y",
		"USE_FILTER" => "Y",
		"FILTER_NAME" => "arrFilter",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "BRAND",
			1 => "",
		),
		"FILTER_PRICE_CODE" => array(
			0 => "BASE",
		),
		"FILTER_OFFERS_FIELD_CODE" => array(
			0 => "ID",
			1 => "",
		),
		"FILTER_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "COLOR",
			2 => "CML2_LINK",
			3 => "",
		),
		"USE_REVIEW" => "Y",
		"MESSAGES_PER_PAGE" => "10",
		"USE_CAPTCHA" => "Y",
		"REVIEW_AJAX_POST" => "Y",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"FORUM_ID" => "1",
		"URL_TEMPLATES_READ" => "",
		"SHOW_LINK_TO_FORUM" => "Y",
		"POST_FIRST_MESSAGE" => "N",
		"USE_COMPARE" => "Y",
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"COMPARE_FIELD_CODE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "",
		),
		"COMPARE_PROPERTY_CODE" => array(
			0 => "BRAND",
			1 => "CML2_ARTICLE",
			2 => "CML2_ATTRIBUTES",
			3 => "",
		),
		"COMPARE_OFFERS_FIELD_CODE" => array(
			0 => "ID",
			1 => "",
		),
		"COMPARE_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "COLOR",
			2 => "CML2_LINK",
			3 => "",
		),
		"COMPARE_ELEMENT_SORT_FIELD" => "sort",
		"COMPARE_ELEMENT_SORT_ORDER" => "asc",
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_PROPERTIES" => array(
		),
		"USE_PRODUCT_QUANTITY" => "Y",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "UAH",
		"OFFERS_CART_PROPERTIES" => array(
			0 => "CML2_ARTICLE",
		),
		"SHOW_TOP_ELEMENTS" => "N",
		"SECTION_COUNT_ELEMENTS" => "Y",
		"SECTION_TOP_DEPTH" => "2",
		"SECTIONS_LIST_PREVIEW_PROPERTY" => "UF_SECTION_DESCR",
		"SHOW_SECTION_LIST_PICTURES" => "Y",
		"PAGE_ELEMENT_COUNT" => "40",
		"LINE_ELEMENT_COUNT" => "3",
		"ELEMENT_SORT_FIELD" => "shows",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER2" => "desc",
		"LIST_PROPERTY_CODE" => array(
			0 => "BRAND",
			1 => "CML2_ARTICLE",
			2 => "CML2_LINK",
			3 => "",
		),
		"INCLUDE_SUBSECTIONS" => "Y",
		"LIST_META_KEYWORDS" => "-",
		"LIST_META_DESCRIPTION" => "-",
		"LIST_BROWSER_TITLE" => "NAME",
		"LIST_OFFERS_FIELD_CODE" => array(
			0 => "ID",
			1 => "NAME",
			2 => "CML2_LINK",
			3 => "",
		),
		"LIST_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "COLOR",
			2 => "CML2_LINK",
			3 => "",
		),
		"LIST_OFFERS_LIMIT" => "5",
		"SORT_BUTTONS" => array(
			0 => "POPULARITY",
			1 => "NAME",
			2 => "PRICE",
		),
		"SORT_PRICES" => "MINIMUM_PRICE",
		"DEFAULT_LIST_TEMPLATE" => "list",
		"SECTION_DISPLAY_PROPERTY" => "UF_SECTION_TEMPLATE",
		"LIST_DISPLAY_POPUP_IMAGE" => "Y",
		"SECTION_PREVIEW_PROPERTY" => "UF_SECTION_DESCR",
		"SHOW_SECTION_PICTURES" => "Y",
		"SHOW_SECTION_SIBLINGS" => "Y",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "VIDEO_YOUTUBE",
			1 => "BRAND",
			2 => "SERVICES",
			3 => "CML2_ARTICLE",
			4 => "CML2_BASE_UNIT",
			5 => "HIT",
			6 => "RECOMMEND",
			7 => "NEW",
			8 => "STOCK",
			9 => "VIDEO",
			10 => "SERVICES",
			11 => "",
		),
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_BROWSER_TITLE" => "NAME",
		"DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "ID",
			1 => "NAME",
			2 => "",
		),
		"DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "CML2_ARTICLE",
			1 => "COLOR",
			2 => "CML2_LINK",
			3 => "",
		),
		"PROPERTIES_DISPLAY_LOCATION" => "DESCRIPTION",
		"SHOW_BRAND_PICTURE" => "Y",
		"SHOW_ASK_BLOCK" => "Y",
		"ASK_FORM_ID" => "2",
		"SHOW_ADDITIONAL_TAB" => "Y",
		"PROPERTIES_DISPLAY_TYPE" => "TABLE",
		"SHOW_KIT_PARTS" => "Y",
		"SHOW_KIT_PARTS_PRICES" => "Y",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_IBLOCK_ID" => "",
		"LINK_PROPERTY_SID" => "",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"USE_ALSO_BUY" => "Y",
		"ALSO_BUY_ELEMENT_COUNT" => "5",
		"ALSO_BUY_MIN_BUYES" => "2",
		"USE_STORE" => "Y",
		"USE_STORE_PHONE" => "Y",
		"USE_STORE_SCHEDULE" => "Y",
		"USE_MIN_AMOUNT" => "Y",
		"MIN_AMOUNT" => "10",
		"IBLOCK_BANNERS_TYPE" => "aspro_kshop_adv",
		"IBLOCK_BANNERS_ID" => "3",
		"IBLOCK_BANNERS_TYPE_ID" => "2",
		"IBLOCK_SMALL_BANNERS_TYPE_ID" => "4",
		"STORE_PATH" => "/contacts/stores/#store_id#/",
		"MAIN_TITLE" => "Наличие на складах",
		"MAX_AMOUNT" => "20",
		"USE_ONLY_MAX_AMOUNT" => "Y",
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "desc",
		"PAGER_TEMPLATE" => "",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"IBLOCK_STOCK_ID" => "8",
		"SHOW_QUANTITY" => "Y",
		"SHOW_MEASURE" => "Y",
		"SHOW_QUANTITY_COUNT" => "Y",
		"USE_RATING" => "Y",
		"DISPLAY_WISH_BUTTONS" => "Y",
		"DEFAULT_COUNT" => "1",
		"SHOW_HINTS" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "N",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE_PATH#/",
			"element" => "#SECTION_CODE_PATH#/#ELEMENT_ID#/",
			"compare" => "compare.php?action=#ACTION_CODE#",
		),
		"VARIABLE_ALIASES" => array(
			"compare" => array(
				"ACTION_CODE" => "action",
			),
		)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
<?/*require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Каталог");
$APPLICATION->IncludeComponent("bitrix:catalog", "main", array(
	"IBLOCK_TYPE" => "aspro_kshop_catalog",
	"IBLOCK_ID" => "11",
	"HIDE_NOT_AVAILABLE" => "N",
	"BASKET_URL" => "/basket/",
	"ACTION_VARIABLE" => "action",
	"PRODUCT_ID_VARIABLE" => "id",
	"SECTION_ID_VARIABLE" => "SECTION_ID",
	"PRODUCT_QUANTITY_VARIABLE" => "quantity",
	"PRODUCT_PROPS_VARIABLE" => "prop",
	"SEF_MODE" => "Y",
	"SEF_FOLDER" => "/catalog/",
	"AJAX_MODE" => "N",
	"AJAX_OPTION_JUMP" => "N",
	"AJAX_OPTION_STYLE" => "Y",
	"AJAX_OPTION_HISTORY" => "N",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "250000",
	"CACHE_FILTER" => "N",
	"CACHE_GROUPS" => "Y",
	"SET_TITLE" => "Y",
	"SET_STATUS_404" => "Y",
	"USE_ELEMENT_COUNTER" => "Y",
	"USE_FILTER" => "Y",
	"FILTER_NAME" => "arrFilter",
		"FILTER_FIELD_CODE" => array(0=>"",1=>"",),
		"FILTER_PROPERTY_CODE" => array(0=>"",1=>"BRAND",2=>"",),
		"FILTER_PRICE_CODE" => array(0=>"BASE",),
	"FILTER_OFFERS_FIELD_CODE" => array(
		0 => "ID",
		1 => "",
	),
	"FILTER_OFFERS_PROPERTY_CODE" => array(
		0 => "COLOR",
		1 => "CML2_LINK",
		2 => "",
	),
	"USE_REVIEW" => "Y",
	"MESSAGES_PER_PAGE" => "10",
	"USE_CAPTCHA" => "Y",
	"REVIEW_AJAX_POST" => "Y",
	"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
	"FORUM_ID" => "1",
	"URL_TEMPLATES_READ" => "",
	"SHOW_LINK_TO_FORUM" => "Y",
	"POST_FIRST_MESSAGE" => "N",
	"USE_COMPARE" => "Y",
	"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
	"COMPARE_FIELD_CODE" => array(
		0 => "PREVIEW_PICTURE",
		1 => "",
	),
	"COMPARE_PROPERTY_CODE" => array(
		0 => "BRAND",
	),
	"COMPARE_OFFERS_FIELD_CODE" => array(
		0 => "ID",
		1 => "",
	),
	"COMPARE_OFFERS_PROPERTY_CODE" => array(
		0 => "COLOR",
		1 => "CML2_LINK",
		2 => "",
	),
	"COMPARE_ELEMENT_SORT_FIELD" => "sort",
	"COMPARE_ELEMENT_SORT_ORDER" => "asc",
	"DISPLAY_ELEMENT_SELECT_BOX" => "N",
	"PRICE_CODE" => array(
		0 => "BASE",
	),
	"USE_PRICE_COUNT" => "N",
	"SHOW_PRICE_COUNT" => "1",
	"PRICE_VAT_INCLUDE" => "Y",
	"PRICE_VAT_SHOW_VALUE" => "N",
	"PRODUCT_PROPERTIES" => array(
	),
	"USE_PRODUCT_QUANTITY" => "Y",
	"CONVERT_CURRENCY" => "Y",
	"CURRENCY_ID" => "RUB",
	"OFFERS_CART_PROPERTIES" => array(
		0 => "COLOR",
	),
	"SHOW_TOP_ELEMENTS" => "N",
	"SECTION_COUNT_ELEMENTS" => "Y",
	"SECTION_TOP_DEPTH" => "2",
	"SECTIONS_LIST_PREVIEW_PROPERTY" => "UF_SECTION_DESCR",
	"SHOW_SECTION_LIST_PICTURES" => "Y",
	"PAGE_ELEMENT_COUNT" => "40",
	"LINE_ELEMENT_COUNT" => "3",
	"ELEMENT_SORT_FIELD" => "shows",
	"ELEMENT_SORT_ORDER" => "asc",
	"ELEMENT_SORT_FIELD2" => "id",
	"ELEMENT_SORT_ORDER2" => "desc",
	"LIST_PROPERTY_CODE" => array(
		0 => "BRAND",
		1 => "CML2_ARTICLE",
		2 => "CML2_LINK",
	),
	"INCLUDE_SUBSECTIONS" => "Y",
	"LIST_META_KEYWORDS" => "-",
	"LIST_META_DESCRIPTION" => "-",
	"LIST_BROWSER_TITLE" => "-",
	"LIST_OFFERS_FIELD_CODE" => array(
		0 => "ID",
		1 => "CML2_LINK",
		2 => "",
	),
	"LIST_OFFERS_PROPERTY_CODE" => array(
		0 => "COLOR",
		1 => "CML2_LINK",
		2 => "",
	),
	"LIST_OFFERS_LIMIT" => "5",
	"SORT_BUTTONS" => array(
		0 => "POPULARITY",
		1 => "NAME",
		2 => "PRICE",
	),
	"SORT_PRICES" => "MINIMUM_PRICE",
	"DEFAULT_LIST_TEMPLATE" => "list",
	"SECTION_DISPLAY_PROPERTY" => "UF_SECTION_TEMPLATE",
	"LIST_DISPLAY_POPUP_IMAGE" => "Y",
	"SECTION_PREVIEW_PROPERTY" => "UF_SECTION_DESCR",
	"SHOW_SECTION_PICTURES" => "Y",
	"SHOW_SECTION_SIBLINGS" => "Y",
	"DETAIL_PROPERTY_CODE" => array(
		0 => "HIT",
		1 => "RECOMMEND",
		2 => "NEW",
		3 => "STOCK",
		4 => "BRAND",
		5 => "PROP_2033",
		6 => "PROP_2055",
		7 => "PROP_157",
		8 => "PROP_158",
		9 => "PROP_159",
		10 => "CML2_ARTICLE",
		11 => "CML2_BASE_UNIT",
		12 => "PROP_2059",
		13 => "VIDEO_YOUTUBE",
		14 => "PROP_248",
		15 => "SERVICES",
		16 => "PROP_244",
		17 => "PROP_181",
		18 => "PROP_206",
		19 => "PROP_162",
		20 => "PROP_209",
		21 => "PROP_198",
		22 => "PROP_2085",
		23 => "PROP_2052",
		24 => "PROP_2069",
		25 => "PROP_2057",
		26 => "PROP_2004",
		27 => "PROP_2082",
		28 => "PROP_2027",
		29 => "PROP_2053",
		30 => "PROP_2051",
		31 => "PROP_2077",
		32 => "PROP_2083",
		33 => "PROP_2049",
		34 => "PROP_2028",
		35 => "PROP_2035",
		36 => "PROP_2029",
		37 => "PROP_2064",
		38 => "PROP_2013",
		39 => "PROP_2008",
		40 => "PROP_2015",
		41 => "PROP_2014",
		42 => "PROP_2026",
		43 => "PROP_2044",
		44 => "PROP_2081",
		45 => "PROP_2006",
		46 => "PROP_2073",
		47 => "PROP_2011",
		48 => "PROP_2065",
		49 => "PROP_2002",
		50 => "PROP_2062",
		51 => "PROP_2003",
		52 => "PROP_2054",
		53 => "PROP_2043",
		54 => "PROP_2047",
		55 => "PROP_2058",
		56 => "PROP_2045",
		57 => "PROP_2072",
		58 => "PROP_2010",
		59 => "PROP_2009",
		60 => "PROP_2017",
		61 => "PROP_2061",
		62 => "PROP_2007",
		63 => "PROP_2056",
		64 => "PROP_2046",
		65 => "PROP_2005",
		66 => "PROP_2060",
		67 => "PROP_2001",
		68 => "VIDEO",
		69 => "SERVICES",
		70 => "",
	),
	"DETAIL_META_KEYWORDS" => "-",
	"DETAIL_META_DESCRIPTION" => "-",
	"DETAIL_BROWSER_TITLE" => "-",
	"DETAIL_OFFERS_FIELD_CODE" => array(
		0 => "ID",
		1 => "",
	),
	"DETAIL_OFFERS_PROPERTY_CODE" => array(
		0 => "COLOR",
		1 => "CML2_LINK",
		2 => "",
	),
	"PROPERTIES_DISPLAY_LOCATION" => "DESCRIPTION",
	"SHOW_BRAND_PICTURE" => "Y",
	"SHOW_ASK_BLOCK" => "Y",
	"ASK_FORM_ID" => "2",
	"SHOW_ADDITIONAL_TAB" => "Y",
	"PROPERTIES_DISPLAY_TYPE" => "TABLE",
	"SHOW_KIT_PARTS" => "Y",
	"SHOW_KIT_PARTS_PRICES" => "Y",
	"LINK_IBLOCK_TYPE" => "",
	"LINK_IBLOCK_ID" => "",
	"LINK_PROPERTY_SID" => "",
	"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
	"USE_ALSO_BUY" => "Y",
	"ALSO_BUY_ELEMENT_COUNT" => "5",
	"ALSO_BUY_MIN_BUYES" => "2",
	"USE_STORE" => "Y",
	"USE_STORE_PHONE" => "Y",
	"USE_STORE_SCHEDULE" => "Y",
	"USE_MIN_AMOUNT" => "Y",
	"MIN_AMOUNT" => "10",
	"IBLOCK_BANNERS_TYPE" => "aspro_kshop_adv",
	"IBLOCK_BANNERS_ID" => "3",
	"IBLOCK_BANNERS_TYPE_ID" => "2",
	"IBLOCK_SMALL_BANNERS_TYPE_ID" => "4",
	"STORE_PATH" => "/contacts/stores/#store_id#/",
	"MAIN_TITLE" => "Наличие на складах",
	"MAX_AMOUNT" => "20",
	"USE_ONLY_MAX_AMOUNT" => "Y",
	"OFFERS_SORT_FIELD" => "sort",
	"OFFERS_SORT_ORDER" => "asc",
	"OFFERS_SORT_FIELD2" => "id",
	"OFFERS_SORT_ORDER2" => "desc",
	"PAGER_TEMPLATE" => "",
	"DISPLAY_TOP_PAGER" => "N",
	"DISPLAY_BOTTOM_PAGER" => "Y",
	"PAGER_TITLE" => "Товары",
	"PAGER_SHOW_ALWAYS" => "N",
	"PAGER_DESC_NUMBERING" => "N",
	"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
	"PAGER_SHOW_ALL" => "N",
	"IBLOCK_STOCK_ID" => "8",
	"SHOW_QUANTITY" => "Y",
	"SHOW_MEASURE" => "Y",
	"SHOW_QUANTITY_COUNT" => "Y",
	"USE_RATING" => "Y",
	"DISPLAY_WISH_BUTTONS" => "Y",
	"DEFAULT_COUNT" => "1",
	"SHOW_HINTS" => "Y",
	"AJAX_OPTION_ADDITIONAL" => "",
	"SEF_URL_TEMPLATES" => array(
		"sections" => "",
		"section" => "#SECTION_CODE_PATH#/",
		"element" => "#SECTION_CODE_PATH#/#ELEMENT_ID#/",
		"compare" => "compare.php?action=#ACTION_CODE#",
	),
	"VARIABLE_ALIASES" => array(
		"compare" => array(
			"ACTION_CODE" => "action",
		),
	)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");*/?>