<?
$arSectionCodeForNewCatalog = array(
	'krupnaya_domashnyaya_tekhnika',
	'kholodilniki_dlya_vina',
	'ledogeneratory_1',
	'vesy_napolnye',
	'parogeneratory',
	'radiochasy_i_meteostantsii',
	'chasy_nastennye',
	'shveynye_mashiny',
	'mikrovolnovye_pechi',
	'pylesosy',
	'stiralnye_mashiny',
	'sushilnye_mashiny_i_barabany',
	'kholodilniki',
	'malaya_domashnyaya_tekhnika',
	'gladilnye_doski',
	'gladilnye_sistemy',
	'svetilniki',
	'utyugi',
	'klimaticheskaya_tekhnika',
	'ventilyatory',
	'vodonagrevateli',
	'konditsionery',
	'obogrevatelnye_pribory',
	'sistemy_obrabotki_vozdukha',
	'elektrogeneratory_i_instrumenty',
	'generatory',
	'instrumenty',
	'aksessuary_dlya_dom_tekhniki',
	'na_udalenie',
	'bytovaya_tekhnika',

    'televizory_audio_video',
    'televizory',
	'led_televizory',
	'plazmennye_televizory',
	'blu_ray_domashnie_kinoteatry',
	'domashnie_kinoteatry',
	'blu_ray_pleery',
	'dvd_pleery',
	'dvd_portativnye',
	'proektory_i_aksessuary',
	'videoregistratory',
	'radar_detektory',
	


	'hi_fi_tekhnika',
	'mp3_pleery',
	'magnitoly',
	'muzykalnye_tsentry',
	'klavishnye',
	'strunnye',
	'aksessuary_dlya_audio',
	'aksessuary_dlya_tv',
	'aksessuary_dlya_muz_instrumentov',



    'videokamery_fotoapparaty',
	'aksessuary_dlya_foto_video_1',
	'batarei_i_zaryadki',
	'karty_pamyati',
	'obektivy_linzy',
	'sumki_dlya_foto_video',
	'fotovspyshki',
	'videokamery',
	'fotoapparaty_zerkalnye',
	'fotoapparaty_kompaktnye',
	'fotoapparaty_sistemnye',
	'tsifrovye_fotoramki',


    // встраиваемая техника
    'vstraivaemaya_tekhnika',
    'vstraivaemye_kholodilniki',
    'vstraivaemye_stiralnye_mashiny',
    'vstraivaemye_posudomoechnye_mashiny',
    'vstraivaemye_poverkhnosti',
    'vstraivaemye_dukhovki',
    'vstraivaemye_vytyazhki',
    'vstraivaemye_mikrovolnovye_pechi',
    'prochaya_vstraivaemaya_tekhnika',

    // красота и здоровье
    'tovary_dlya_krasoty',
    'britvy',
    'vypryamiteli',
    'manikyurnye_nabory',
    'massazhery',
    'mashinki_dlya_strizhki_trimmery',
    'ployki',
    'staylery',
    'fen_shchyetki',
    'feny',
    'epilyatory',
    'vesy',
    'tovary_dlya_zdorovya',
    'vanny_dlya_nog',
    'vesy_napolnye_1',
    'zerkala',
    'zubnye_shchyetki',
    'ukhod_za_volosami',
    'ukhod_za_litsom',
    'ukhod_za_nogtyami',
    'elektrogrelki',
    'elektronnye_bide',
    'tovary_dlya_detey',
    'detskoe_tvorchestvo',
    'kormlenie',
    'mame_v_pomoshch',
    'prigotovlenie',
    'radio_nyani',
    'razvitie',
    'ukhod_za_rebyenkom',
    'aksessuary_1',

    //=СЦЕПИТЬ("'";G2;"',")

    //кухонная техника
    'krupnaya_kukh_tekhnika',
    'ledogeneratory',
    'mikrovolnovye_pechi_2',
    'elektropechi_i_plitki',
    'plity',
    'posudomoechnye_mashiny_1',
    'kholodilniki_2',
    'piknik',
    'malaya_kukh_tekhnika',
    'blendery_pogruzhnye',
    'blendery_statsionarnye',
    'kukhonnye_kombayny',
    'miksery',
    'multivarki',
    'dispensery',
    'myasorubki',
    'parovarki',
    'posuda',
    'nozhi_i_komlekty_nozhey',
    'prochaya_kukhonnaya_mbt',
    'filtry_dlya_vody',
    'risovarki',
    'sokovyzhimalki',
    'termopot',
    'tostery_sendvichnitsy',
    'frityurnitsy',
    'khlebopechki',
    'chayniki',
    'chaynye_pary',
    'prigotovlenie_kofe',
    'kofe',
    'kofemolki',
    'kofevarki_kofemashiny',
    'aksessuary_dlya_kukh_tekhniki',

    'kompyutery_i_noutbuki_apple',
	'french_press'
);